# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=15, unique=True, verbose_name='N\xfamero de Documento')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(default='+573001234567', max_length=128, null=True, verbose_name='T\xe9lefono')),
                ('direccion', models.CharField(max_length=15, null=True, verbose_name='Direcci\xf3n')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usario')),
            ],
        ),
    ]
