# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-24 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20171024_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
