# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripci\xf3n')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripci\xf3n')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direcci\xf3n')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fechaInicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fechaFinalizacion', models.DateField(verbose_name='Fecha Finalizaci\xf3n')),
                ('formaPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta d\xe9bito', 'Tarjeta d\xe9bito'), ('tarjeta cr\xe9dito', 'Tarjeta cr\xe9dito'), ('venta a cr\xe9dito', 'Venta a cr\xe9dito'), ('bono', 'Bono'), ('vale', 'Vale'), ('otros', 'Otros')], max_length=50, verbose_name='Forma de pago')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('obraActiva', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='detalleobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Obra'),
        ),
        migrations.AddField(
            model_name='detalleobra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='detalleobra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
