# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obrero', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleObreroObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Obra')),
                ('obrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obrero.Obrero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
