# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_detalleobreroobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='porcentajeA',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (11, '11%'), (12, '12%'), (13, '13%'), (14, '14%'), (15, '15%'), (16, '16%'), (17, '17%')], null=True, verbose_name='Porcentaje A'),
        ),
        migrations.AddField(
            model_name='obra',
            name='porcentajeI',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (11, '11%'), (12, '12%'), (13, '13%'), (14, '14%'), (15, '15%'), (16, '16%'), (17, '17%')], null=True, verbose_name='Porcentaje I'),
        ),
        migrations.AddField(
            model_name='obra',
            name='porcentajeU',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0%'), (1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (11, '11%'), (12, '12%'), (13, '13%'), (14, '14%'), (15, '15%'), (16, '16%'), (17, '17%')], null=True, verbose_name='Porcentaje U'),
        ),
        migrations.AddField(
            model_name='obra',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='valorA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Valor A'),
        ),
        migrations.AddField(
            model_name='obra',
            name='valorI',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Valor I'),
        ),
        migrations.AddField(
            model_name='obra',
            name='valorU',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Valor U'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Iva U'),
        ),
    ]
