# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20171117_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleobra',
            name='cantidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='cantidad'),
        ),
    ]
